# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\halechr\repo\looper\gui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(1388, 664)
        window.setMinimumSize(QtCore.QSize(1024, 480))
        window.setStyleSheet("")
        self.widget_central = QtWidgets.QWidget(window)
        self.widget_central.setObjectName("widget_central")
        self.layout_main = QtWidgets.QGridLayout(self.widget_central)
        self.layout_main.setObjectName("layout_main")
        self.entry_video = QtWidgets.QLineEdit(self.widget_central)
        self.entry_video.setAutoFillBackground(False)
        self.entry_video.setReadOnly(True)
        self.entry_video.setObjectName("entry_video")
        self.layout_main.addWidget(self.entry_video, 1, 1, 1, 1)
        self.list_timestamp = TimestampTableView(self.widget_central)
        self.list_timestamp.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.list_timestamp.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_timestamp.setAlternatingRowColors(True)
        self.list_timestamp.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.list_timestamp.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.list_timestamp.setObjectName("list_timestamp")
        self.list_timestamp.horizontalHeader().setHighlightSections(False)
        self.list_timestamp.horizontalHeader().setStretchLastSection(True)
        self.list_timestamp.verticalHeader().setHighlightSections(False)
        self.layout_main.addWidget(self.list_timestamp, 2, 0, 1, 4)
        self.button_video_browse = QtWidgets.QPushButton(self.widget_central)
        self.button_video_browse.setObjectName("button_video_browse")
        self.layout_main.addWidget(self.button_video_browse, 1, 3, 1, 1)
        self.frame_media = QtWidgets.QFrame(self.widget_central)
        self.frame_media.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_media.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_media.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_media.setLineWidth(0)
        self.frame_media.setObjectName("frame_media")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_media)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.media_layout = QtWidgets.QVBoxLayout()
        self.media_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.media_layout.setObjectName("media_layout")
        self.frame_video = VideoFrame(self.frame_media)
        self.frame_video.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_video.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.frame_video.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_video.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_video.setLineWidth(0)
        self.frame_video.setObjectName("frame_video")
        self.media_layout.addWidget(self.frame_video)
        self.frame_media_control = QtWidgets.QFrame(self.frame_media)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_media_control.sizePolicy().hasHeightForWidth())
        self.frame_media_control.setSizePolicy(sizePolicy)
        self.frame_media_control.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_media_control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_media_control.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_media_control.setLineWidth(0)
        self.frame_media_control.setObjectName("frame_media_control")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_media_control)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_play_pause = ToggleButton(self.frame_media_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_play_pause.sizePolicy().hasHeightForWidth())
        self.button_play_pause.setSizePolicy(sizePolicy)
        self.button_play_pause.setCheckable(False)
        self.button_play_pause.setObjectName("button_play_pause")
        self.gridLayout_2.addWidget(self.button_play_pause, 1, 0, 1, 1)
        self.button_mute_toggle = ToggleButton(self.frame_media_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_mute_toggle.sizePolicy().hasHeightForWidth())
        self.button_mute_toggle.setSizePolicy(sizePolicy)
        self.button_mute_toggle.setObjectName("button_mute_toggle")
        self.gridLayout_2.addWidget(self.button_mute_toggle, 1, 13, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 12, 1, 1)
        self.btnRight = QtWidgets.QToolButton(self.frame_media_control)
        self.btnRight.setArrowType(QtCore.Qt.RightArrow)
        self.btnRight.setObjectName("btnRight")
        self.gridLayout_2.addWidget(self.btnRight, 1, 10, 1, 1)
        self.button_slow_down = QtWidgets.QPushButton(self.frame_media_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_slow_down.sizePolicy().hasHeightForWidth())
        self.button_slow_down.setSizePolicy(sizePolicy)
        self.button_slow_down.setObjectName("button_slow_down")
        self.gridLayout_2.addWidget(self.button_slow_down, 1, 2, 1, 1)
        self.slider_volume = HighlightedJumpSlider(self.frame_media_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_volume.sizePolicy().hasHeightForWidth())
        self.slider_volume.setSizePolicy(sizePolicy)
        self.slider_volume.setMaximum(39)
        self.slider_volume.setPageStep(1)
        self.slider_volume.setSliderPosition(20)
        self.slider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.slider_volume.setObjectName("slider_volume")
        self.gridLayout_2.addWidget(self.slider_volume, 1, 14, 1, 1)
        self.btnSkipRight = QtWidgets.QToolButton(self.frame_media_control)
        self.btnSkipRight.setObjectName("btnSkipRight")
        self.gridLayout_2.addWidget(self.btnSkipRight, 1, 11, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 6, 1, 1)
        self.btnLeft = QtWidgets.QToolButton(self.frame_media_control)
        self.btnLeft.setArrowType(QtCore.Qt.LeftArrow)
        self.btnLeft.setObjectName("btnLeft")
        self.gridLayout_2.addWidget(self.btnLeft, 1, 8, 1, 1)
        self.button_mark_end = QtWidgets.QPushButton(self.frame_media_control)
        self.button_mark_end.setObjectName("button_mark_end")
        self.gridLayout_2.addWidget(self.button_mark_end, 1, 4, 1, 1)
        self.slider_progress = HighlightedJumpSlider(self.frame_media_control)
        self.slider_progress.setMaximum(9999)
        self.slider_progress.setPageStep(1)
        self.slider_progress.setOrientation(QtCore.Qt.Horizontal)
        self.slider_progress.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_progress.setObjectName("slider_progress")
        self.gridLayout_2.addWidget(self.slider_progress, 0, 0, 1, 15)
        self.button_full_screen = QtWidgets.QPushButton(self.frame_media_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_full_screen.sizePolicy().hasHeightForWidth())
        self.button_full_screen.setSizePolicy(sizePolicy)
        self.button_full_screen.setObjectName("button_full_screen")
        self.gridLayout_2.addWidget(self.button_full_screen, 1, 5, 1, 1)
        self.button_mark_start = QtWidgets.QPushButton(self.frame_media_control)
        self.button_mark_start.setObjectName("button_mark_start")
        self.gridLayout_2.addWidget(self.button_mark_start, 1, 3, 1, 1)
        self.btnSkipLeft = QtWidgets.QToolButton(self.frame_media_control)
        self.btnSkipLeft.setObjectName("btnSkipLeft")
        self.gridLayout_2.addWidget(self.btnSkipLeft, 1, 7, 1, 1)
        self.button_speed_up = QtWidgets.QPushButton(self.frame_media_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_speed_up.sizePolicy().hasHeightForWidth())
        self.button_speed_up.setSizePolicy(sizePolicy)
        self.button_speed_up.setObjectName("button_speed_up")
        self.gridLayout_2.addWidget(self.button_speed_up, 1, 1, 1, 1)
        self.spinBoxFrameJumpMultiplier = QtWidgets.QSpinBox(self.frame_media_control)
        self.spinBoxFrameJumpMultiplier.setMinimum(1)
        self.spinBoxFrameJumpMultiplier.setMaximum(1000)
        self.spinBoxFrameJumpMultiplier.setObjectName("spinBoxFrameJumpMultiplier")
        self.gridLayout_2.addWidget(self.spinBoxFrameJumpMultiplier, 1, 9, 1, 1)
        self.media_layout.addWidget(self.frame_media_control)
        self.gridLayout.addLayout(self.media_layout, 1, 0, 1, 1)
        self.layout_main.addWidget(self.frame_media, 2, 5, 3, 1)
        self.frame_timestamp_detail = QtWidgets.QFrame(self.widget_central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_timestamp_detail.sizePolicy().hasHeightForWidth())
        self.frame_timestamp_detail.setSizePolicy(sizePolicy)
        self.frame_timestamp_detail.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_timestamp_detail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_timestamp_detail.setObjectName("frame_timestamp_detail")
        self.formLayout = QtWidgets.QFormLayout(self.frame_timestamp_detail)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_start_time = QtWidgets.QLabel(self.frame_timestamp_detail)
        self.label_start_time.setObjectName("label_start_time")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_start_time)
        self.entry_start_time = QtWidgets.QLineEdit(self.frame_timestamp_detail)
        self.entry_start_time.setEnabled(True)
        self.entry_start_time.setAutoFillBackground(False)
        self.entry_start_time.setReadOnly(True)
        self.entry_start_time.setObjectName("entry_start_time")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.entry_start_time)
        self.label_end_time = QtWidgets.QLabel(self.frame_timestamp_detail)
        self.label_end_time.setObjectName("label_end_time")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_end_time)
        self.entry_end_time = QtWidgets.QLineEdit(self.frame_timestamp_detail)
        self.entry_end_time.setEnabled(True)
        self.entry_end_time.setAutoFillBackground(False)
        self.entry_end_time.setReadOnly(True)
        self.entry_end_time.setObjectName("entry_end_time")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.entry_end_time)
        self.label_description = QtWidgets.QLabel(self.frame_timestamp_detail)
        self.label_description.setObjectName("label_description")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_description)
        self.entry_description = PlainTextEdit(self.frame_timestamp_detail)
        self.entry_description.setEnabled(True)
        self.entry_description.setMaximumSize(QtCore.QSize(16777215, 75))
        self.entry_description.setAutoFillBackground(False)
        self.entry_description.setObjectName("entry_description")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.entry_description)
        self.frame = QtWidgets.QFrame(self.frame_timestamp_detail)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_add_entry = QtWidgets.QPushButton(self.frame)
        self.button_add_entry.setObjectName("button_add_entry")
        self.horizontalLayout.addWidget(self.button_add_entry)
        self.button_remove_entry = QtWidgets.QPushButton(self.frame)
        self.button_remove_entry.setEnabled(False)
        self.button_remove_entry.setObjectName("button_remove_entry")
        self.horizontalLayout.addWidget(self.button_remove_entry)
        self.button_save = QtWidgets.QPushButton(self.frame)
        self.button_save.setEnabled(False)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout.addWidget(self.button_save)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.button_run = QtWidgets.QPushButton(self.frame)
        self.button_run.setObjectName("button_run")
        self.horizontalLayout.addWidget(self.button_run)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.frame)
        self.layout_main.addWidget(self.frame_timestamp_detail, 3, 0, 1, 4)
        self.button_timestamp_browse = QtWidgets.QPushButton(self.widget_central)
        self.button_timestamp_browse.setObjectName("button_timestamp_browse")
        self.layout_main.addWidget(self.button_timestamp_browse, 0, 3, 1, 1)
        self.entry_timestamp = QtWidgets.QLineEdit(self.widget_central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_timestamp.sizePolicy().hasHeightForWidth())
        self.entry_timestamp.setSizePolicy(sizePolicy)
        self.entry_timestamp.setAutoFillBackground(False)
        self.entry_timestamp.setStyleSheet("")
        self.entry_timestamp.setReadOnly(True)
        self.entry_timestamp.setObjectName("entry_timestamp")
        self.layout_main.addWidget(self.entry_timestamp, 0, 1, 1, 1)
        self.button_timestamp_create = QtWidgets.QPushButton(self.widget_central)
        self.button_timestamp_create.setObjectName("button_timestamp_create")
        self.layout_main.addWidget(self.button_timestamp_create, 0, 4, 1, 1)
        self.label_video = QtWidgets.QLabel(self.widget_central)
        self.label_video.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_video.setObjectName("label_video")
        self.layout_main.addWidget(self.label_video, 1, 0, 1, 1)
        self.label_timestamp = QtWidgets.QLabel(self.widget_central)
        self.label_timestamp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_timestamp.setObjectName("label_timestamp")
        self.layout_main.addWidget(self.label_timestamp, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_central)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 9, 0, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblVideoName = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblVideoName.setFont(font)
        self.lblVideoName.setObjectName("lblVideoName")
        self.horizontalLayout_3.addWidget(self.lblVideoName)
        self.lblVideoSubtitle = QtWidgets.QLabel(self.widget)
        self.lblVideoSubtitle.setObjectName("lblVideoSubtitle")
        self.horizontalLayout_3.addWidget(self.lblVideoSubtitle)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setEnabled(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_3.addWidget(self.dateTimeEdit)
        self.layout_main.addWidget(self.widget, 0, 5, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget_central)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_7.setContentsMargins(0, 2, 0, 0)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblCurrentFrame_3 = QtWidgets.QLabel(self.groupBox_3)
        self.lblCurrentFrame_3.setObjectName("lblCurrentFrame_3")
        self.horizontalLayout_6.addWidget(self.lblCurrentFrame_3)
        self.lblTotalFrames_3 = QtWidgets.QLabel(self.groupBox_3)
        self.lblTotalFrames_3.setObjectName("lblTotalFrames_3")
        self.horizontalLayout_6.addWidget(self.lblTotalFrames_3)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblCurrentTime = QtWidgets.QLabel(self.groupBox_2)
        self.lblCurrentTime.setObjectName("lblCurrentTime")
        self.horizontalLayout_5.addWidget(self.lblCurrentTime)
        self.lblTotalDuration = QtWidgets.QLabel(self.groupBox_2)
        self.lblTotalDuration.setObjectName("lblTotalDuration")
        self.horizontalLayout_5.addWidget(self.lblTotalDuration)
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblCurrentFrame = QtWidgets.QLabel(self.groupBox)
        self.lblCurrentFrame.setObjectName("lblCurrentFrame")
        self.horizontalLayout_4.addWidget(self.lblCurrentFrame)
        self.lblTotalFrames = QtWidgets.QLabel(self.groupBox)
        self.lblTotalFrames.setObjectName("lblTotalFrames")
        self.horizontalLayout_4.addWidget(self.lblTotalFrames)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.layout_main.addWidget(self.widget_2, 1, 5, 1, 1)
        window.setCentralWidget(self.widget_central)
        self.actionExit = QtWidgets.QAction(window)
        self.actionExit.setObjectName("actionExit")
        self.actionTest_Entry = QtWidgets.QAction(window)
        self.actionTest_Entry.setObjectName("actionTest_Entry")

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Video Loop"))
        self.button_video_browse.setText(_translate("window", "Browse"))
        self.button_play_pause.setToolTip(_translate("window", "Toggle Play/Pause"))
        self.button_play_pause.setText(_translate("window", "Play/Pause"))
        self.button_mute_toggle.setToolTip(_translate("window", "Toggle Mute/Unmute"))
        self.button_mute_toggle.setText(_translate("window", "Mute"))
        self.btnRight.setToolTip(_translate("window", "Jump Frames Right"))
        self.btnRight.setText(_translate("window", ">"))
        self.btnRight.setShortcut(_translate("window", "Right"))
        self.button_slow_down.setToolTip(_translate("window", "Slow down the video"))
        self.button_slow_down.setText(_translate("window", "Slow Down"))
        self.btnSkipRight.setToolTip(_translate("window", "Skip Frames Right"))
        self.btnSkipRight.setText(_translate("window", "->"))
        self.btnSkipRight.setShortcut(_translate("window", "Ctrl+Right"))
        self.btnLeft.setToolTip(_translate("window", "Jump Frames Left"))
        self.btnLeft.setText(_translate("window", "<"))
        self.btnLeft.setShortcut(_translate("window", "Left"))
        self.button_mark_end.setToolTip(_translate("window", "Mark the end of the entry"))
        self.button_mark_end.setText(_translate("window", "Mark End"))
        self.button_full_screen.setToolTip(_translate("window", "Set the video to full screen"))
        self.button_full_screen.setText(_translate("window", "Full Screen"))
        self.button_mark_start.setToolTip(_translate("window", "Mark the start of the entry"))
        self.button_mark_start.setText(_translate("window", "Mark Start"))
        self.btnSkipLeft.setToolTip(_translate("window", "Skip Frames Left"))
        self.btnSkipLeft.setText(_translate("window", "<-"))
        self.btnSkipLeft.setShortcut(_translate("window", "Ctrl+Left"))
        self.button_speed_up.setToolTip(_translate("window", "Speed up the video"))
        self.button_speed_up.setText(_translate("window", "Speed Up"))
        self.label_start_time.setText(_translate("window", "Start Time"))
        self.label_end_time.setText(_translate("window", "End Time"))
        self.label_description.setText(_translate("window", "Description"))
        self.button_add_entry.setText(_translate("window", "Add Entry"))
        self.button_remove_entry.setText(_translate("window", "Remove Entry"))
        self.button_save.setText(_translate("window", "Save"))
        self.button_run.setText(_translate("window", "Run"))
        self.button_timestamp_browse.setText(_translate("window", "Browse"))
        self.button_timestamp_create.setText(_translate("window", "Create"))
        self.label_video.setText(_translate("window", "Video File"))
        self.label_timestamp.setText(_translate("window", "Timestamp File"))
        self.lblVideoName.setText(_translate("window", "VideoName"))
        self.lblVideoSubtitle.setText(_translate("window", "Subtitle"))
        self.groupBox_3.setTitle(_translate("window", "Other"))
        self.lblCurrentFrame_3.setText(_translate("window", "00000"))
        self.lblTotalFrames_3.setText(_translate("window", "00000"))
        self.groupBox_2.setTitle(_translate("window", "Playback Time"))
        self.lblCurrentTime.setText(_translate("window", "00000"))
        self.lblTotalDuration.setText(_translate("window", "00000"))
        self.groupBox.setTitle(_translate("window", "Video Frames"))
        self.lblCurrentFrame.setText(_translate("window", "00000"))
        self.lblTotalFrames.setText(_translate("window", "00000"))
        self.actionExit.setText(_translate("window", "Exit"))
        self.actionTest_Entry.setText(_translate("window", "Test Entry"))

from gui import HighlightedJumpSlider, PlainTextEdit, TimestampTableView, ToggleButton, VideoFrame
